language: generic
sudo: required
services:
    -dockerfile

before_install:
  #build docker image
  - docker build -t madalynharger/docker-react-sample -f Dockerfile.dev . 


script:
  - docker run -e CI=true madalynharger/docker-react-sample npm run test -- --coverage