language: generic
sudo: required
services:
    -docker

before_install:
  #build docker image
  - docker build -t madalynharger/docker-react-sample -f Dockerfile.dev . 


script:
  - docker run -e CI=true madalynharger/docker-react-sample npm run test -- --coverage

deploy:
  #Travis CI is preconfigured to deploy to some providers
  provider: elasticbeanstalk
  edge: true
  region: "us-east-2"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-us-east-2-668238319068"
  bucket_path: "docker-react-sample"
  #only deploy when pushed to master
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY